# Generated by Django 3.2.8 on 2021-11-26 15:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_assignment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='link',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 15, 13, 31, 835353, tzinfo=utc)),
        ),
    ]
