# Generated by Django 3.2.8 on 2021-11-27 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20211127_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='email',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='name',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 15, 44, 6, 900694, tzinfo=utc)),
        ),
    ]
