# Generated by Django 3.2.8 on 2021-11-27 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20211127_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 17, 30, 59, 849645, tzinfo=utc)),
        ),
    ]
