# Generated by Django 3.2.8 on 2021-11-27 19:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_assignment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Assignment',
        ),
        migrations.AddField(
            model_name='feedback',
            name='AssignmentSubmission',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='core.assignmentsubmission'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 19, 9, 26, 378964, tzinfo=utc)),
        ),
    ]
