# Generated by Django 3.2.8 on 2021-11-28 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_auto_20211128_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 12, 39, 10, 840446, tzinfo=utc)),
        ),
    ]
