# Generated by Django 3.2.8 on 2021-11-28 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_alter_assignment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 28, 13, 40, 43, 551209, tzinfo=utc)),
        ),
    ]
